services:
    web:
        image: webapp:latest
        ports:
            - "5000:5000"
    db:
        image: postgres:latest
        environment:
            POSTGRES_DB: mydatabase
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
